---
- hosts: "{{ play_host_groups }}"
  serial: yes
  gather_facts: "{{gather_facts_for_pb | default(false)}}"
  tasks:
  - name: run shell command
    shell: "{{ shell_command }}"
    register: task_result_to_output
    ignore_errors: "{{skip_errors | default('omit')}}"

