---
- hosts: "{{ play_host_groups }}"
  serial: yes
  gather_facts: "{{gather_facts_for_pb | default(false)}}"
  tasks:
  - name: run shell command
    shell: "{{ shell_command }}"
    register: task_result_to_output
    ignore_errors: yes
  - name: fail the task when not skipping errors
    fail:
      msg: "the task failed and skip_errors={{skip_errors|bool}}"
    when: (not skip_errors|bool) and (task_result_to_output is not success)
  - include: write_task_output_to_file.yml
